Add backend code to get token - iOS
microsoft/immersive-reader-sdk pull request #376
Opened 2022-05-10 14:25 UTC by cristobal-buenrostro

2022-05-31 13:07 UTC, rwallerms requested changes

2022-07-20 18:29 UTC, cristobal-buenrostro commented on js/samples/ios/README.md
> +1. In case you want to have the iOS sample getting the token from the back end code.Cd into the **server** folder and then [refer to public node server sample here](https://github.com/microsoft/immer
revised

2022-07-20 18:31 UTC, cristobal-buenrostro commented on js/samples/ios/quickstart-swift/LaunchViewController.swift
> +        let tokenUrl = self.isTokenFromServer ? self.tokenServerUrl! : "https://login.windows.net/" + self.tenantId! + "/oauth2/token"
new var added

2022-07-20 18:32 UTC, cristobal-buenrostro commented on js/samples/ios/quickstart-swift/LaunchViewController.swift
> +    private var tokenServerUrl = ProcessInfo.processInfo.environment["TOKEN_SERVER_URL"]
yeah, makes sense, value removed from config and handled now as variable

2022-07-20 18:32 UTC, cristobal-buenrostro commented on js/samples/ios/quickstart-swift/LaunchViewController.swift
> +        if(!self.isTokenFromServer){
agree, changed

2022-07-21 03:45 UTC, rwallerms approved these changes

2022-07-22 22:00 UTC, merged